# Data Science & Machine Learning Internship Assignment II

Perform the following operations using the given two arrays.
A1=[11,33,22,44,66,55]
A2=[10,30,20,40,60,50]

1.   Extract the elements of array A1 from the index 2 to 5
2.   Reshape the array A1 into (3,2) size.
3.   Join the two arrays A1 and A2.
4.   Split the array A1 into 3 arrays.
5.   Search for a number 44 in the array A1
6.   Print all the even numbers of array A1 using search option.
7.   Sort the numbers of array A2.
8.   Filter the odd numbers in the array A1 using filter option.

In [1]:
#Array Creation
import numpy as np
arr1 = np.array([11,33,22,44,66,55])
arr2 = np.array([10,30,20,40,60,50])
print(arr1)
print(arr2)

[11 33 22 44 66 55]
[10 30 20 40 60 50]


In [3]:
# 1. Extract the elements of array A1 from the index 2 to 5
print(arr1[2:6])
print(arr1[2:])

[22 44 66 55]
[22 44 66 55]


In [5]:
# 2. Reshape the array A1 into (3,2) size.
newarr = arr1.reshape(3,2)
print(newarr)

[[11 33]
 [22 44]
 [66 55]]


In [10]:
# 3. Join the two arrays A1 and A2
print("combining the arrays")
print(np.concatenate((arr1,arr2)))

combining the arrays
[11 33 22 44 66 55 10 30 20 40 60 50]


In [11]:
# 4. Split the array A1 into 3 arrays
print(np.array_split(arr1,3))

[array([11, 33]), array([22, 44]), array([66, 55])]


In [12]:
# 5. Search for a number 44 in the array A1
print(np.where(arr1 == 4))

(array([], dtype=int64),)


In [15]:
# 6. Print all the even numbers of array A1 using search option.
even_index = np.where(arr1 % 2 == 0)
for i in even_index:
    print(arr1[i])

[22 44 66]


In [16]:
# 7. Sort the numbers of array A2.
print(np.sort(arr2))

[10 20 30 40 50 60]


In [17]:
# 8. Filter the odd numbers in the array A1 using filter option.
odd_num = arr1 % 2 != 0
print(arr1[odd_num])

[11 33 55]
