In [1]:
import numpy as np 
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.dtype)
print(arr1.ndim)

[1 2 3 4 5]
int32
1


In [2]:
import numpy as np 
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr2)
print(arr2.dtype)
print(arr2.ndim)

[[1 2 3 4 5]
 [6 7 8 9 0]]
int32
2


In [3]:
import numpy as np 
arr3 = np.array([[[1,2,3,4,5],[6,7,8,9,0],[1,2,3,4,5]]])
print(arr3)
print(arr3.dtype)
print(arr3.ndim)

[[[1 2 3 4 5]
  [6 7 8 9 0]
  [1 2 3 4 5]]]
int32
3


In [4]:
#Array slicing
print(arr1[1:3])

[2 3]
